server:
  port: 8080

spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:      
        - id: students
          uri: http://localhost:8001
          predicates:
            - Path=/api/students/**

        - id: courses
          uri: http://localhost:8002
          predicates:
            - Path=/api/courses/**
          
